[package]
name = "dec_2"
version = "0.1.0"
authors = ["SKyletoft <45131343+SKyletoft@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
